### ISSUE TITLE
cells_matrix.npy not found

### ISSUE THREAD

**Issue by MrArthor** [DamianoBrunori/UAV_RL_Thesis#5]
when the env_wrapper is tried to run it's giving an error that "FileNotFoundError: [Errno 2] No such file or directory: './map_data/cells_matrix.npy'".

**Comment by DamianoBrunori** [comment]
This is due to the fact that the files must be run in the following order (as specified in README file):

  - scenario_objects.py
  - plotting.py
  - env_wrapper.py

**Comment by MrArthor** [comment]
Thanks for the support. Actually it was due to some version issue with
threadpooltc package of python, the default version didn't properly
supported the requirements of the kMeans cluster. Which i later resolved by
uninstalling and then reinstalling the forementioned package. And i would
like to say sorry for the inconveniences caused by me.

Your Sincerely
Vansh Sachdeva
